### PR TITLE
Quick fix in RobotMap.cpp

### PR DESCRIPTION
**Pull request by Alexbay218**
Must merge to master before someone uses navx methods!
Merge as soon as possible!!!

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Can you please fix your commit title and PR name? This makes our repo look very unprofessional and is just in general bad. Champ agrees.

Also, please remove the date from your commit messages.

**Comment by WardBenjamin** [comment]
Other than that, the actual content is good.

**Comment by WardBenjamin** [comment]
What's the status on this?

**Comment by Alexbay218** [comment]
For some reason, code will deploy but not run

**Pull request closed without merging**
