### PR TITLE
Dev-navx-nolib merge to master

### PR DESCRIPTION
**Pull request by Alexbay218**
Will compile on my computer and on Champ's. Objective is to get navx code working for other robot code. Obstacles are the other libraries required for working code. Fixed by including Navx library in 612-2016/src/Libraries/Navx. Fixed all conflicts (Master branch has priority over d-navx-nolib).

### CODE REVIEW

**Comment by Alexbay218** [comment]
4,755+ lines, but not even a tenth are mine. I just included a library as to not destroy everyone's computers.

**Comment by toastertaster** [comment]
@Alexbay218 #37 is a blocker to this pull request.

**Comment by Alexbay218** [comment]
Code works and compiles on multiple laptops. Navx Board does work with this code. No libraries required to be installed.

**Comment by WardBenjamin** [comment]
@Alexbay218 Looks good, but probably should have waited for myself, Champ, Travis, or another senior member who can do code review to merge.

**Comment by Alexbay218** [comment]
Did not do this on purpose, Dr. Axtell reverted master branch to before this merge. I meant to merge master to dev-navx-nolib

**Pull request merged**
